document.write("<hr style=\"margin: 30pt 0pt 0pt;\">");
document.write("<p style=\"margin: 10pt 100pt 0pt; text-align: justify; line-height: normal;\">");
document.write("<i>");
document.write("©[Copyright]");
document.write("<\/i><\/p>");
document.write("<p style=\"margin: 0pt 100pt 10pt; text-align: justify; line-height: normal;\">");
document.write("<i>");
document.write("Esto es un footer de prueba creado desde JavaScript");
document.write(" para añadir a una página html.");
document.write("<\/i><\/p>");
document.write("<hr>");